# Generated by Django 2.2.7 on 2025-04-01 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20250401_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='secret_info',
            field=models.TextField(blank=True),
        ),
    ]
